import asyncio
import json
import sys
from typing import List, Dict, Any
from io import StringIO
from core.nest import Nest

class NestREPL:
    """
    RLM Environment that allows the model to interact with the Nest.
    Provides safe exec/eval with tool registry.
    """
    def __init__(self):
        self.tools = {
            "query": Nest.query,
            "fetch": self._fetch,
            "ingest": Nest.ingest,
        }
    
    async def _fetch(self, key: str) -> Any:
        """Fetch data by key from Nest"""
        results = await Nest.query(f"Fetch {key}", top_k=1)
        return results[0] if results else None

    async def execute(self, code: str) -> str:
        """
        Executes code generated by the RLM safely.
        Provides tools in the global namespace.
        """
        # Capture stdout
        old_stdout = sys.stdout
        sys.stdout = buffer = StringIO()
        
        try:
            # Build restricted globals
            globals_dict = {
                "nest": Nest,
                "tools": self.tools,
                "query": self.tools["query"],
                "fetch": self.tools["fetch"],
                "json": json,
                "asyncio": asyncio,
                "print": print,
            }
            
            # Execute code
            if "await" in code:
                # Wrap async code
                wrapped = f"async def __rlm_wrapper():\n" + "\n".join(f"    {line}" for line in code.split("\n"))
                exec(wrapped, globals_dict)
                result = await globals_dict["__rlm_wrapper"]()
            else:
                exec(code, globals_dict)
                result = None
            
            output = buffer.getvalue()
            sys.stdout = old_stdout
            
            if result is not None:
                return f"{output}Result: {result}".strip()
            return output.strip() or "Execution successful"
            
        except Exception as e:
            sys.stdout = old_stdout
            return f"Error: {str(e)}"
        finally:
            sys.stdout = old_stdout
